baseURL = ""
languageCode = "ja"
defaultContentLanguage = "ja"
title = "Masateru Horiuchi"
assetDir = "./assets/"
enableEmoji = true
disableKinds = ["taxonomyTerm", "taxonomy"]

[permalinks]
    post = "/:year/:month/:day/:slug"

[params]
    author = "Masateru Horiuchi"
    location = "Tokyo"
    site_description = "Masateru Horiuchi's Gallery"
    description = "Masateru Horiuchi's Gallery"
    images = ["images/main.gif"]
    copyright  = "Masateru Horiuchi All Rights Reserved"
    logo = "images/favicon.ico"
    date_format = "2006-01-02"

